version: '2'
services:
  web:
    image: registry.heroku.com/visual-hacker-news/web
    build: .
    restart: always
    mem_limit: 2G
    memswap_limit: 0
    command: 'node --harmony-async-await --optimize_for_size --max_old_space_size=460 --gc_interval=100 server.js'
    working_dir: /usr/src/app
    depends_on:
      - redis
    links: 
      - redis
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      REDIS_URL: ${REDIS_URL}
    ports:
      - '${PORT}:${PORT}'
    volumes: 
      - /tmp/thumbnails:/usr/src/app/public/thumbnails
      - ./fetchImages.js:/usr/src/app/fetchImages.js
      - ./server.js:/usr/src/app/server.js
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"